### ISSUE TITLE
Two finger scrolling + Sensors

### ISSUE THREAD

**Issue by basicinside** [longsleep/yoga3pro-linux#1]
Hi,

have you tried to enable more advanced touchpad features like two finger scrolling?

Did you had a chance to test the sensors drivers from https://github.com/pfps/yoga-laptop ?

**Comment by longsleep** [comment]
I have dumped the Yoga 3. Use Kernel 4.0 which has all the drivers including those you linked. 

Two finger scrolling was working fine - this is a pretty standard feature.
