### ISSUE TITLE
use 1600x900 resolution

### ISSUE THREAD

**Issue by hying-caritas** [longsleep/yoga3pro-linux#4]
Just FYI.

http://community.linuxmint.com/tutorial/view/877

I tried to set the resolution to 1600x900 according to the above article.  It appears help some application and help save power.

**Comment by longsleep** [comment]
Yeah well i am not a big fan to reduce power by running low resolution. It is better to get a laptop with a full hd display if you want long battery life. Thanks for the comment though.
